// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSession() {
  return window['go']['main']['App']['CheckSession']();
}

export function CreateTable(arg1, arg2) {
  return window['go']['main']['App']['CreateTable'](arg1, arg2);
}

export function DetailDataTournament(arg1) {
  return window['go']['main']['App']['DetailDataTournament'](arg1);
}

export function FetchDetailScoreTournament(arg1, arg2) {
  return window['go']['main']['App']['FetchDetailScoreTournament'](arg1, arg2);
}

export function FetchDetailTournamentMatch(arg1, arg2) {
  return window['go']['main']['App']['FetchDetailTournamentMatch'](arg1, arg2);
}

export function FetchLog(arg1) {
  return window['go']['main']['App']['FetchLog'](arg1);
}

export function FetchScoreTurnament(arg1) {
  return window['go']['main']['App']['FetchScoreTurnament'](arg1);
}

export function GetDetailTournamentMatch(arg1) {
  return window['go']['main']['App']['GetDetailTournamentMatch'](arg1);
}

export function GetListTable(arg1, arg2) {
  return window['go']['main']['App']['GetListTable'](arg1, arg2);
}

export function GetRegisteredPlayers(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetRegisteredPlayers'](arg1, arg2, arg3, arg4);
}

export function GetTournamentMatchList(arg1, arg2) {
  return window['go']['main']['App']['GetTournamentMatchList'](arg1, arg2);
}

export function InputTournament(arg1, arg2, arg3) {
  return window['go']['main']['App']['InputTournament'](arg1, arg2, arg3);
}

export function InputTournamentMatchScore(arg1, arg2) {
  return window['go']['main']['App']['InputTournamentMatchScore'](arg1, arg2);
}

export function IsBotRunning() {
  return window['go']['main']['App']['IsBotRunning']();
}

export function ListMatch(arg1, arg2) {
  return window['go']['main']['App']['ListMatch'](arg1, arg2);
}

export function ListTournament(arg1) {
  return window['go']['main']['App']['ListTournament'](arg1);
}

export function LoginRiichiApi(arg1, arg2) {
  return window['go']['main']['App']['LoginRiichiApi'](arg1, arg2);
}

export function LogoutRiichi() {
  return window['go']['main']['App']['LogoutRiichi']();
}

export function SendPlayerInvite(arg1) {
  return window['go']['main']['App']['SendPlayerInvite'](arg1);
}

export function StartBot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartBot'](arg1, arg2, arg3, arg4);
}

export function StartTable(arg1) {
  return window['go']['main']['App']['StartTable'](arg1);
}

export function StopBot() {
  return window['go']['main']['App']['StopBot']();
}

export function SubmitDetailTournamentMatch(arg1, arg2) {
  return window['go']['main']['App']['SubmitDetailTournamentMatch'](arg1, arg2);
}

export function SubmitPoint(arg1, arg2) {
  return window['go']['main']['App']['SubmitPoint'](arg1, arg2);
}
