// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTable(arg1, arg2) {
  return window['go']['main']['App']['CreateTable'](arg1, arg2);
}

export function DetailTournament(arg1) {
  return window['go']['main']['App']['DetailTournament'](arg1);
}

export function FetchDetailScoreTournament(arg1, arg2) {
  return window['go']['main']['App']['FetchDetailScoreTournament'](arg1, arg2);
}

export function FetchScoreTurnament(arg1) {
  return window['go']['main']['App']['FetchScoreTurnament'](arg1);
}

export function InputTournament(arg1, arg2, arg3) {
  return window['go']['main']['App']['InputTournament'](arg1, arg2, arg3);
}

export function InputTournamentMatchScore(arg1, arg2) {
  return window['go']['main']['App']['InputTournamentMatchScore'](arg1, arg2);
}

export function IsBotRunning() {
  return window['go']['main']['App']['IsBotRunning']();
}

export function ListMatch(arg1) {
  return window['go']['main']['App']['ListMatch'](arg1);
}

export function ListTournament(arg1) {
  return window['go']['main']['App']['ListTournament'](arg1);
}

export function LoginRiichiApi(arg1, arg2) {
  return window['go']['main']['App']['LoginRiichiApi'](arg1, arg2);
}

export function SendPlayerInvite(arg1) {
  return window['go']['main']['App']['SendPlayerInvite'](arg1);
}

export function StartBot(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartBot'](arg1, arg2, arg3, arg4);
}

export function StartTable(arg1) {
  return window['go']['main']['App']['StartTable'](arg1);
}

export function StopBot() {
  return window['go']['main']['App']['StopBot']();
}
