// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function DetailTournament(arg1:number):Promise<database.Tournament>;

export function Greet(arg1:string):Promise<string>;

export function InputTournament(arg1:number,arg2:string,arg3:string):Promise<database.Tournament>;

export function IsBotRunning():Promise<boolean>;

export function ListTournament(arg1:database.PaginationTournament):Promise<Array<database.Tournament>>;

export function LoginRiichiApi(arg1:string,arg2:string):Promise<void>;

export function SendPlayerInvite(arg1:number):Promise<void>;

export function StartBot(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StartTable(arg1:number):Promise<void>;

export function StopBot():Promise<void>;
