// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {riichicommand} from '../models';

export function CheckSession():Promise<boolean>;

export function CreateTable(arg1:number,arg2:Array<number>):Promise<void>;

export function DetailDataTournament(arg1:number):Promise<database.Tournament>;

export function FetchDetailScoreTournament(arg1:string,arg2:string):Promise<void>;

export function FetchDetailTournamentMatch(arg1:string,arg2:string):Promise<void>;

export function FetchLog(arg1:string):Promise<riichicommand.Log>;

export function FetchScoreTurnament(arg1:number):Promise<void>;

export function GetDetailTournamentMatch(arg1:string):Promise<database.TournamentMatch>;

export function GetListTable(arg1:number,arg2:database.PaginationMatch):Promise<Array<database.Match>>;

export function GetRegisteredPlayers(arg1:boolean,arg2:number,arg3:string,arg4:database.Pagination):Promise<Array<database.RegisterTournament>>;

export function GetTournamentMatchList(arg1:number,arg2:database.PaginationTournament):Promise<Array<database.TournamentMatch>>;

export function InputTournament(arg1:number,arg2:string,arg3:string):Promise<database.Tournament>;

export function InputTournamentMatchScore(arg1:number,arg2:number):Promise<void>;

export function IsBotRunning():Promise<boolean>;

export function ListMatch(arg1:number,arg2:database.PaginationMatch):Promise<Array<database.Match>>;

export function ListTournament(arg1:database.PaginationTournament):Promise<Array<database.Tournament>>;

export function LoginRiichiApi(arg1:string,arg2:string):Promise<void>;

export function LogoutRiichi():Promise<void>;

export function PlayRandomMatch(arg1:number):Promise<void>;

export function SendPlayerInvite(arg1:number):Promise<void>;

export function StartBot(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StartTable(arg1:number):Promise<void>;

export function StopBot():Promise<void>;

export function SubmitDetailTournamentMatch(arg1:number,arg2:number):Promise<void>;

export function SubmitPoint(arg1:number,arg2:number):Promise<void>;
